### ISSUE TITLE
Paper Bins have to be click-dragged onto the player to remove from trash piles

### ISSUE THREAD

**Issue by Ashturian** [SyzygyStation/Syzygy-Eris#44]
The default use for paper bins prompts you to take paper from the bin

**Comment by Ashturian** [comment]
App

**Comment by Ashturian** [comment]
Thoughts on either swapping the click-drag and default click uses, or to just have paper bins not show up in scrap?

**Comment by ShadzFen** [comment]
The thing is, having a paperbin in your backpack is something you can do if you're going to be dealing out paper often. Clicking it in your backpack and having it give you a sheet of paper rather than pulling the whole bin out seems intentional. Dragging it onto your character is not that big of a deal anyway. 

Removing paper bins from trash piles is certainly a possibility though, but it seems like effort for something that isn't really that big of an issue.

Unless anyone else is very adamant about this, I'm gonna close the issue within the next few days.

**Comment by Ashturian** [comment]
Click-dragging is a little more prevalent on Eris than other codebases, so maybe people will be more inclined to try it, but I don't think it's good design when people will be removing things from piles with left click for every single other case except this one particular item. I think the click-drag and in-hand use should remove paper from the trays, and left click to pick it up would bring it in line with things like device cells

**Comment by ShadzFen** [comment]
In order to keep things consistent, it's gonna be left as is, since changing it will cause more inconvenience overall than leaving it as it is. An exception could be made but it would be kindof tedious. Make a suggestion ticket for it if you want, but for now this ticket is gonna be tagged as non-issue and closed.
