### ISSUE TITLE
Drones can't alt-click tiles anymore to see the turf.

### ISSUE THREAD

**Issue by subtumaka** [SyzygyStation/Syzygy-Eris#63]
#### Description of issue
Drones can no longer alt-click tiles to see a list of all the things on the turf. The turf tab does not even appear in the top right.

#### Difference between expected and actual behavior
Before the addition to let drones ventcrawl, they could still alt-click tiles but after that addition, they cannot. 

#### Steps to reproduce 
Be maint-drone
Alt-click any tile
*buzz at not being able to click things that are under other things.

#### Length of time in which bug has been known to occur
It worked fine before the fix that allowed maint-drones to vent crawl
It does not work anymore after that

#### Client version, Server revision & Game ID
BYOND: 513.1528
Revision: Master - 316465cda6de6fd2934eec6aafc17b6130bf94e7

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by martinlyra** [comment]
This actually seems to be an actual intended effect that's applied to *ALL* synthetics. But I can go and make an edit that enables all robots, including drones, to view the contents of turf when alt-clicking on them.

Because right now you do only get a list of contents when you alt-click on a vent to crawl in it. That'll open the turf tab with the contents.
